<a href="https://colab.research.google.com/github/Njeriee/machine_learning_series/blob/main/introduction_to_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# TensorFlow is an end-to-end platform for machine learning
# It supports the following
# a) Multidimensional-array based numeric computation (similar to NumPy.)
# b) GPU and distributed processing
# c) Automatic differentiation
# d) Model construction, training, and export
# And more

In [ ]:
# TensorFlow operates on multidimensional arrays or tensors represented as tf.Tensor objects

In [ ]:
import tensorflow as tf

In [ ]:
# example of tensors belonging to diffrent dimensions
# rank zero tensor/scalar it is just a point(zero dimensions)
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# rank 1 tensor/vector(1 dimension)
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
# rank 2 tensor/matrix(2 dimensions)
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
# @title Default title text
# rank 3 tensor/3D (3-dimensions)
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
# rank 4 tensor
rank_4_tensor = tf.zeros([3, 2, 4, 5])

print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [ ]:
# dimensions are sometimes called axis(axes in plr)
# tensors may have more than 3 axes i.e it is possible to create tensors that are beyond 3D

In [ ]:
# You can convert a tensor to a NumPy array either using np.array or the tensor.numpy method
# e.g
import numpy as np
print(np.array(rank_2_tensor))
# you don't have to import numpy to use this
print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
# you can do basic math operations on tensors
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

print(tf.add(a, b), "\n") # addition
print(tf.multiply(a, b), "\n") # multiplication
print(tf.matmul(a, b), "\n") # matrix multiplication

# or
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [ ]:
# you can also do a bunch of other stuff on tensors
# eg
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

# softmax is a function of the neural network (nn) module found in tensorflow
# what softmax does
# a) Exponentiates -  It takes each element of c and raises it to the power of Euler's number (e), creating a vector of positive values.i.e coverts all values to positive numbers
# b) Normalizes - divides each exponentiated element by the sum of all exponentiated elements, resulting in a vector(all values add up to 1)
# c) Interpretation - The resulting values can be interpreted as probabilities, indicating the relative likelihood of each class or category.


tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [ ]:
# Indexing
# TensorFlow follows standard Python indexing rules, similar to indexing a list or a string in Python, and the basic rules for NumPy indexing.

# indexes start at 0
# negative indices count backwards from the end
# colons, :, are used for slices: start:stop:step

In [ ]:
# rank 1 tensors/vectors are typically lists and can be indexed as such
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

# indexing
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

# slicing
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

In [ ]:
# for ranks 2 and above indexing is done through passing a list
# eg
print(rank_2_tensor.numpy())

# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
# indexing a rank 3 tensor
print(rank_3_tensor)

print(rank_3_tensor[:, :, 4])

In [ ]:
# ragged tensor example
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

#converting it into a tensor
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)


In [ ]:
# string tensors
# tf.string is a dtype, which is to say you can represent data as strings (variable-length byte arrays) in tensors.
# The strings are atomic and cannot be indexed the way Python strings are
# eg
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

# a tensor/vector of strings
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

# there are more functions to manipulate string tensors(check documentation)

In [ ]:
# sparse tensors
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))