<a href="https://colab.research.google.com/github/Njeriee/machine_learning_series/blob/main/tensor_shapes_and_reshapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
# here we generate a tensor of only ones to play around with.Remember to include the shape and the dimension of the tensor
t = tf.ones([3,2,1])
print(t)
print(tf.rank(t))

tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
# you can also generate a tensor of zeros using the deafult tf.zeros method of tensorflow
t2 = tf.zeros([2,2])
print(t2)
# to reshape a tensor keep in mind the number of elements it has
# i.e to reshape the above tensor we know that it has 4 elements i.e 2*2 we can carry out the operation using the tf.reshape() method
print(tf.reshape(t2,[4]))
print(rank)
# the above code line flattens the array and returns a flattened array which is a list with 4 elements

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float32)
